version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: mybot_postgres
    restart: always
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: botdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  bot:
    build: .
    container_name: mybot_container
    depends_on:
      - postgres
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      DATABASE_URL: "${DATABASE_URL}"
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
    volumes:
      - .:/app
volumes:
  pg_data:
  sqlite_data: